# Generated by Django 5.1.1 on 2025-02-18 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('crowd_count', models.IntegerField(blank=True, null=True)),
                ('month_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('Zone', models.CharField(blank=True, max_length=200, null=True)),
                ('Type', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Year', models.CharField(blank=True, max_length=200, null=True)),
                ('Time_needed', models.CharField(blank=True, max_length=200, null=True)),
                ('Google_rating', models.CharField(blank=True, max_length=200, null=True)),
                ('Significance', models.CharField(blank=True, max_length=200, null=True)),
                ('Best_time_to_visit', models.CharField(blank=True, max_length=200, null=True)),
                ('Fees', models.CharField(blank=True, max_length=200, null=True)),
                ('Image_url', models.URLField(blank=True, max_length=30000, null=True)),
                ('map_url', models.TextField(blank=True, db_column='map_url', null=True)),
                ('crowd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.crowdmodel')),
            ],
        ),
        migrations.AddField(
            model_name='crowdmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.placemode'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you_City', models.CharField(blank=True, max_length=200, null=True)),
                ('you_State', models.CharField(blank=True, max_length=200, null=True)),
                ('fav_type', models.CharField(blank=True, max_length=200, null=True)),
                ('fav_significance', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(blank=True, max_length=50, null=True)),
                ('review_description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.placemode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='crowdmodel',
            unique_together={('location', 'month')},
        ),
    ]
