# Generated by Django 5.1.1 on 2025-03-05 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tripreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreview',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.placemode'),
        ),
    ]
