# Generated by Django 5.1.1 on 2025-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tripreview_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreview',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
