# Generated by Django 5.1.1 on 2025-03-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreview',
            name='no_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
