# Generated by Django 5.1.1 on 2025-03-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tripreview_no_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreview',
            name='image_url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
