# Generated by Django 5.1.1 on 2025-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemode',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
